Document: check-ice2
Title: Debian check-ice2 Manual
Author: <insert document author here>
Abstract: This manual describes what check-ice2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/check-ice2/check-ice2.sgml.gz

Format: postscript
Files: /usr/share/doc/check-ice2/check-ice2.ps.gz

Format: text
Files: /usr/share/doc/check-ice2/check-ice2.text.gz

Format: HTML
Index: /usr/share/doc/check-ice2/html/index.html
Files: /usr/share/doc/check-ice2/html/*.html
